
package com.chuangye.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bs_service", targetNamespace = "http://tempurl.org", wsdlLocation = "http://10.6.0.33:8088/bs_service/bs_service.asmx?WSDL")
public class BsService
    extends Service
{

    private final static URL BSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BSSERVICE_EXCEPTION;
    private final static QName BSSERVICE_QNAME = new QName("http://tempurl.org", "bs_service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.0.33:8088/bs_service/bs_service.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSSERVICE_WSDL_LOCATION = url;
        BSSERVICE_EXCEPTION = e;
    }

    public BsService() {
        super(__getWsdlLocation(), BSSERVICE_QNAME);
    }

    public BsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSSERVICE_QNAME, features);
    }

    public BsService(URL wsdlLocation) {
        super(wsdlLocation, BSSERVICE_QNAME);
    }

    public BsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSSERVICE_QNAME, features);
    }

    public BsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BsServiceSoap
     */
    @WebEndpoint(name = "bs_serviceSoap")
    public BsServiceSoap getBsServiceSoap() {
        return super.getPort(new QName("http://tempurl.org", "bs_serviceSoap"), BsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BsServiceSoap
     */
    @WebEndpoint(name = "bs_serviceSoap")
    public BsServiceSoap getBsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempurl.org", "bs_serviceSoap"), BsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSSERVICE_EXCEPTION!= null) {
            throw BSSERVICE_EXCEPTION;
        }
        return BSSERVICE_WSDL_LOCATION;
    }

}
