
package com.chuangye.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bs_serviceSoap", targetNamespace = "http://tempurl.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BsServiceSoap {


    /**
     * 
     * @param asTrademsg
     * @param asTradetype
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/runservice")
    @WebResult(name = "runserviceResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "runservice", targetNamespace = "http://tempurl.org", className = "Runservice")
    @ResponseWrapper(localName = "runserviceResponse", targetNamespace = "http://tempurl.org", className = "RunserviceResponse")
    public String runservice(
            @WebParam(name = "as_tradetype", targetNamespace = "http://tempurl.org")
            String asTradetype,
            @WebParam(name = "as_trademsg", targetNamespace = "http://tempurl.org")
            String asTrademsg);

}
